<?php
require_once('MVC\model\manager\DbManager.php');
require_once('MVC\model\manager\ArticleManager.php');
require_once('MVC\model\manager\CommentManager.php');
require_once('MVC\model\class\Article.php');
require_once('MVC\model\class\Comment.php');
require_once('MVC\controler\DefaultController.php');
require_once('MVC\controler\ArticleController.php');
require_once('MVC\controler\CommentController.php');